# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-10-20 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnbParis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('host_id', models.IntegerField()),
                ('host_name', models.CharField(max_length=100)),
                ('neighbourhood_group', models.CharField(max_length=100)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('room_type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('minimum_nights', models.IntegerField()),
                ('number_of_reviews', models.IntegerField()),
                ('last_review', models.DateTimeField()),
                ('reviews_per_month', models.FloatField()),
                ('calculated_host_listings_count', models.IntegerField()),
                ('availability_365', models.FloatField()),
            ],
        ),
    ]
